// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SixConsult.Funcionarios.Web.Data;

namespace SixConsult.Funcionarios.Web.Migrations
{
    [DbContext(typeof(FuncionarioContext))]
    [Migration("20220407201423_Funcionarios")]
    partial class Funcionarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SixConsult.Funcionarios.Classes.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FuncionarioModelId")
                        .HasColumnType("integer");

                    b.Property<string>("ddd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tipoTelefone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioModelId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("SixConsult.Funcionarios.Web.FuncionarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<string>("numeroChapa")
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.Property<string>("sobrenome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("SixConsult.Funcionarios.Classes.Telefone", b =>
                {
                    b.HasOne("SixConsult.Funcionarios.Web.FuncionarioModel", null)
                        .WithMany("telefones")
                        .HasForeignKey("FuncionarioModelId");
                });

            modelBuilder.Entity("SixConsult.Funcionarios.Web.FuncionarioModel", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
